#!/usr/bin/env bash

# bnuller:
#
# A simple wrapper which allows us to utilize nullmailer for sending email from
# bacula.
#
# Example usage:
# mailcommand = "/usr/local/sbin/bnuller \"Bacula: %t %e of %c %l\" bacula.admin@somedomain.foo"
# Note: This assumes that you have installed this script under /usr/local/sbin
#
# (C) Antti Antinoja 2018

usage_exit() {
	printf "Usage:\n"
	printf "bnuller [Subject] [Receiver email address] ([Sender email address])\n"
	echo ""
	exit 1
}

compose_mail() {
	(
	echo "From: ${SENDER}"
	echo "To: ${ADMIN}"
	echo "Subject: ${SUBJECT}"
	echo ""
	while read MSGLINE ; do
		echo $MSGLINE
	done
	) | sendmail -t
}

if [ -z "${2}" ] || [ -z "${1}" ]; then
	usage_exit
else
	ADMIN=${2}
	SUBJECT=${1}
	if [ -z "${3}" ]; then
		SENDER="bacula-dir"
	else
		SENDER="${3}"
	fi
fi

compose_mail
